### ISSUE TITLE
Écriture de l'outil JOINCACHE

### ISSUE THREAD

**Issue by Dolite** [rok4/pytools#3]

**Comment by CorentinPeutin** [comment]
3 rôles pour l'outil :
- MASTER : faire les contrôles, identifier le travail, répartir en N TODOLIST
- AGENT : récupérer une TODOLIST puis traiter chaque ligne
- FINISHER : récupérer les TODOLIST, écrire la liste et le descripteur de la pyramide en sortie et nettoyage des TODOLIST

**Comment by CorentinPeutin** [comment]
Entrée de l'outil : 
Définition des pyramides à utiliser pour chaque groupe de niveaux de zoom. Pour chaque groupe, la pyramide référencée en premier est la pyramide la plus importante et ainsi de suite.
Toutes les pyramides utilisées pour le Joincache doivent avoir le même TMS, le même nombre de tuilles par dalles, même caractéristiques et même nombre de canaux. Pour les niveaux définis, vérifier que les pyramides sont définis à tous ceux-ci.

**Comment by CorentinPeutin** [comment]
Fonctionnement global de l'outil : 
Pour chaque niveau
  Pour chaque source
    Pour chaque dalle de la source
      Traitées ? -> next
      Pour chaque source moins prioritaire
        Dalle présente ?
      Dalle à générer avec des dalles sources (+ masques)
      Si 1 dalle -> Lien symbolique
      Si plusieurs dalles -> récupérer les dalles -> cache2work (+ masques)
                                        Fussioner                 -> overlayNtiff
                                        Ecrire la dalle finale  -> work2cache (+ masque)

**Comment by CorentinPeutin** [comment]
- [ ] Fichier de configuration
- [ ] Chargement des pyramides
- [ ] Contrôle des pyramides
- [ ] Rôle MASTER
- [ ] Rôle AGENT
- [ ] Rôle FINISHER
- [ ] Documentation
- [ ] Tests unitaires

**Comment by Dolite** [comment]
J'ai poussé la nouvelle structure et le schéma JSON (ainsi qu'un exemple).

**Comment by Dolite** [comment]
Modifications poussées :

- Récupération des modifications sur develop
- Récupération de la mise à niveau de la CI (identique à celle dans core-python)
- Utilisation de `get_levels` de `Pyramid` pour tester la présence des niveaux d'utilisation dans la pyramide source
- Correction du schéma JSON : la section process est bien dans les properties
- Passage en anglais du schéma JSON
- Changement du chargement du schéma JSON (RefResolver est déprécié)
- Ajout de la valeur par défaut pour `only_links`
- Initialisation de variable à None plutôt que False si le but est d'y stocker une instance ou une chaîne
- Détection d'un nom de cluster S3 dans le nom de bucket et sortie en erreur
- Correction de l'écriture du fichier liste : on doit bien inclure les racines des pyramides sources si des liens sont fait vers elles. La liste de ces racines est écrite par le master dans un todo a destination du finisher

Reste à faire :

- [ ] Les identifiants des niveaux sont des chaînes de caractères, on ne peut pas les parcourir par addition
- [ ] Dans la todo list, il n'est finalement pas nécessaire de préciser, pour w2c et c2w, MASK ou DATA : le chemin de la dalle permet de le savoir (méthode `get_infos_from_slab_path` de `Pyramid`)
- [ ] Est ce qu'il ne serait pas possible de ne pas distinguer `SourcePyramids` et `SourceRasterPyramids` (et avoir juste `SourcePyramids` qui s'adapte, comme on a une seule classe `Pyramid` qui gère les deux types) : on vérifierait alors que toutes les pyramides ont le même type, comme on vérifie d'autre caractéristiques communes. On pourra avoir le type de la source = type des pyramides (comme pour le reste) et vérifier dans Joincache que la source est bien de type RASTER
- [ ] Ajouter de la documentation sur les fonctions dans les classes `Source` et compléter les exceptions émises par les différents fonctions `work`
- [ ] Une erreur lors d'un appel à une commande système (au niveau de l'agent) doit faire sortir le script en erreur
- [ ] Renommer le fichier `source.py` -> `Source.py` par homogénéité
- [ ] Le nommage des variables doit être en anglais et en snake case
- [ ] Le contrôle des tailles des dalles dans les pyramides source doit être fait dans le constructeur (et plus besoin de le vérifier dans `info_level`)
- [ ] Fusionner `list_generator_level` dans `list_generator` on y ajoutant un paramètre level optionnel
